In [15]:
import numpy as np
a=np.array(43)
a

array(43)

In [3]:
a

array(43)

In [4]:
a.shape

()

In [5]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [6]:
b.shape

(4,)

In [7]:
c=np.array([[1,2,3],[3,4,5],[6,4,3]])
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 4, 3]])

In [15]:
c.shape

(3, 3)

In [16]:
c[1,1]

4

In [17]:
d=np.array([1,2,3])
d[2]

3

In [21]:
arr1=np.arange(start=1,stop=10,step=2)
arr1

array([1, 3, 5, 7, 9])

In [22]:
arr1

array([1, 3, 5, 7, 9])

In [23]:
arr1=arr1.reshape(5,1)

In [24]:
arr1

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [25]:
arr1=arr1.reshape(-1)
arr1

array([1, 3, 5, 7, 9])

In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr=arr.reshape(3,3)

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr=arr.reshape(-1,1)

In [14]:
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [26]:
ap=np.random.rand(3,2) #generating an array filled with random values


In [27]:
ap

array([[0.9423073 , 0.86266976],
       [0.15663441, 0.67310907],
       [0.71008989, 0.75022997]])

In [28]:
d=np.ones((2,3))

In [29]:
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
e=np.zeros((2,3))

In [32]:
e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
e.dtype

dtype('float64')

In [33]:
for i in np.nditer(d):
    print(i)

1.0
1.0
1.0
1.0
1.0
1.0


In [35]:
arr1=np.array([1,2,3,4])

In [39]:
arr2=np.array([5,6,7,8,3,5])

In [40]:
arr3=np.concatenate((arr1,arr2))

In [41]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 3, 5])

In [55]:
arr3=np.array([[3,6],[9,10]])

In [56]:
arr4=np.array([[2,3],[5,6]])

In [57]:
arr5=np.concatenate((arr2,arr3),axis=0) #joing two array vertically

In [58]:
arr5

array([[ 3,  6],
       [ 9, 10],
       [ 3,  6],
       [ 9, 10]])

In [59]:
arr6=np.concatenate((arr2,arr3),axis=1) #joining two array horizontally

In [60]:
arr6

array([[ 3,  6,  3,  6],
       [ 9, 10,  9, 10]])

In [61]:
arr6=np.append(arr6,[[12,13,14,15]],axis=0) #adding row at the end of an array

In [62]:
arr6

array([[ 3,  6,  3,  6],
       [ 9, 10,  9, 10],
       [12, 13, 14, 15]])

In [70]:
new_col=np.array([[56,75,89]])

In [71]:
new_col=new_col.reshape(3,1)

In [74]:
new_col

array([[56],
       [75],
       [89]])

In [75]:
arr6=np.append(arr6,new_col,axis=1)

In [73]:
arr6

array([[ 3,  6,  3,  6, 56],
       [ 9, 10,  9, 10, 75],
       [12, 13, 14, 15, 89]])

In [81]:
arr6=np.insert(arr6,1,[[90,91,92,93,94,98]],axis=0)

In [82]:
arr6

array([[ 3,  6,  3,  6, 56, 56],
       [90, 91, 92, 93, 94, 98],
       [90, 91, 92, 93, 94, 98],
       [ 9, 10,  9, 10, 75, 75],
       [12, 13, 14, 15, 89, 89]])

In [90]:
arr6=np.insert(arr6,1,[[90,91,92,93,94]],axis=1)

In [91]:
arr6

array([[ 3, 90,  6,  3,  6, 56, 56],
       [90, 91, 91, 92, 93, 94, 98],
       [90, 92, 91, 92, 93, 94, 98],
       [ 9, 93, 10,  9, 10, 75, 75],
       [12, 94, 13, 14, 15, 89, 89]])

In [93]:
arr6=np.delete(arr6,1,axis=0) #deleting row

In [94]:
arr6

array([[ 3, 90,  6,  3,  6, 56, 56],
       [90, 92, 91, 92, 93, 94, 98],
       [ 9, 93, 10,  9, 10, 75, 75],
       [12, 94, 13, 14, 15, 89, 89]])

In [95]:
arr6=np.delete(arr6,2,axis=1) #deleting a column

In [96]:
arr6

array([[ 3, 90,  3,  6, 56, 56],
       [90, 92, 92, 93, 94, 98],
       [ 9, 93,  9, 10, 75, 75],
       [12, 94, 14, 15, 89, 89]])

In [97]:
a1=np.array([5,6,7,8])

In [98]:
a2=np.array([5,6,10,12])

In [99]:
np.add(a1,a2)

array([10, 12, 17, 20])

In [100]:
np.subtract(a1,a2)

array([ 0,  0, -3, -4])

In [101]:
np.multiply(a1,a2)

array([25, 36, 70, 96])

In [102]:
np.divide(a1,a2)

array([1.        , 1.        , 0.7       , 0.66666667])

In [103]:
np.remainder(a1,a2)

array([0, 0, 7, 8])

In [5]:
#data types in numpy
arr3=np.array([1,2,3,4],dtype='S')

In [6]:
arr3

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [8]:
arr4=np.array([1,2,3,4],dtype='U11')

In [9]:
arr4

array(['1', '2', '3', '4'], dtype='<U11')

In [13]:
arr4=arr4.astype('f')

In [14]:
arr4

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.mean(arr)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('S1'), dtype('S1')) -> None

In [58]:
import pandas as pd

In [44]:
df=pd.DataFrame({"Names":["john","alfred","rohit"],"city":["lucknow","delhi","kolkata"]})
df

Names     city
0    john  lucknow
1  alfred    delhi
2   rohit  kolkata

In [45]:
age=[23,24,26]

In [52]:
df['age']=age

In [53]:
df

Names     city  age
0    john  lucknow   23
1  alfred    delhi   24
2   rohit  kolkata   26

In [54]:
df["Names"]

0      john
1    alfred
2     rohit
Name: Names, dtype: object

In [55]:
df.iloc[[1,2]]

Names     city  age
1  alfred    delhi   24
2   rohit  kolkata   26

In [56]:
df=df.drop(['city'],axis=1,inplace=True)

In [43]:
df

Names  age
0   john   23
2  rohit   26

In [37]:
df.drop([1],axis=0,inplace=True)

In [38]:
df

Names  age
0   john   23
2  rohit   26

In [69]:
new_row=pd.DataFrame({"Name":"pooja","age":30},index=[0])

In [70]:
df=pd.concat([df,new_row]).reset_index(drop=True)

In [71]:
new_row1=pd.DataFrame({"Name":"ram","age":32},index=[0])

In [72]:
df=pd.concat([df,new_row1]).reset_index(drop=True)

In [74]:
df

Name  age
0  pooja   30
1  pooja   30
2  pooja   30
3    ram   32

In [75]:
df.drop(2,inplace=True)

In [76]:
df

Name  age
0  pooja   30
1  pooja   30
3    ram   32

In [77]:
for i,j in df.iterrows():
    print(i)
    print(j)

0
Name    pooja
age        30
Name: 0, dtype: object
1
Name    pooja
age        30
Name: 1, dtype: object
3
Name    ram
age      32
Name: 3, dtype: object


In [80]:
for i,j in df.items():
    print(i)
    print(j)

Name
0    pooja
1    pooja
3      ram
Name: Name, dtype: object
age
0    30
1    30
3    32
Name: age, dtype: int64


In [81]:
for column in df:
    colval=df[column]
    print(column)
    print(colval.values)

Name
['pooja' 'pooja' 'ram']
age
[30 30 32]


In [92]:
df=pd.read_csv("/Users/admin/Desktop/User_Data.csv")

In [93]:
df=pd.DataFrame(df)

In [94]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [95]:
df.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [96]:
df.tail(10)

User ID  Gender  Age  EstimatedSalary  Purchased
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [97]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [101]:
df[df["EstimatedSalary"]>30000]

User ID  Gender  Age  EstimatedSalary  Purchased
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
..        ...     ...  ...              ...        ...
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[343 rows x 5 columns]

In [103]:
df[df["EstimatedSalary"]>30000 & (df['Purchased']==1)]

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [104]:
df[df["EstimatedSalary"]>30000 | (df['Purchased']==1)]

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

#value_counts()


In [105]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [106]:
#question
df2=pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],'attempts':[1,3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})


In [107]:
df2

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [110]:
df2[df2["attempts"]>2]

name  score  attempts qualify
1     Dima    9.0         3      no
3    James    NaN         3      no
5  Michael   20.0         3     yes

In [112]:
df2["attempts"].sum()

19

In [113]:
df2

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

#inserting dataframe into excel file

In [ ]:
writer=pd.ExcelWriter("/Users/admin/Desktop/User_Data.csv")